apiVersion: v1
kind: Service
metadata:
  name: thangnh35-capstone-app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: thangnh35-capstone-app
    version: 1-0
  type: LoadBalancer